In [183]:
from IPython.display import display_pretty, display_html, display_jpeg, display_png, display_json, display_latex, display_svg


In [228]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

In [236]:
import numpy as np
large_width = 400
np.set_printoptions(linewidth=large_width)

In [230]:
np.set_printoptions(precision=3)

In [1]:
import numpy as np

In [296]:
edges =[
    [6,10],
    [6,1],
    [10,7],
    [10,1],
    [7,1],
    [7,5],
    [5,2],
    [5,3],
    [1,2],
    [2,3],
    [5,8],
    [3,4],
    [5,8],
    [8,9],
    [8,4],
    [8,11],
    [11,4],
    [4,9],
    [11,9],
    [11,12],
    [12,11],
    [12,9],
]

In [297]:
N = np.zeros((13,13))

In [298]:
for e in edges : 
    N[e[0],e[1]] = 1
    N[e[1],e[0]] = 1

In [299]:
A=N[1:,:][:,1:]

In [300]:
B=A + np.identity(12)

In [301]:
M=col_norm(B)

In [303]:
M_G3=np.matmul(B,B.T)


In [304]:
import copy

In [305]:
def gamma_operation (M, r):
    M_new = copy.deepcopy(M.T)
    
    for i, row in enumerate(M_new) :
        M_new[i] = M_new[i] ** r / sum(row **r )
    return M_new.T

In [306]:
def col_norm (M):
    M_new = copy.deepcopy(M.T)
    for i, row in enumerate(M_new) :
        M_new[i] = M_new[i] / sum(row)
    return M_new.T

In [307]:
def power_matrix (M,r) :
    M_new = copy.deepcopy(M)
    for i in range(r-1) : 
        M_new = np.matmul(M_new, M)
    return M_new


$
\Gamma_2 M^2, 
$

In [309]:
M_1=gamma_operation(power_matrix(M,2),2)

In [310]:
M_1

array([[0.38 , 0.087, 0.027, 0.   , 0.077, 0.295, 0.201, 0.   , 0.   , 0.32 , 0.   , 0.   ],
       [0.047, 0.347, 0.21 , 0.017, 0.15 , 0.019, 0.066, 0.011, 0.   , 0.012, 0.   , 0.   ],
       [0.014, 0.21 , 0.347, 0.055, 0.15 , 0.   , 0.016, 0.046, 0.009, 0.   , 0.009, 0.   ],
       [0.   , 0.027, 0.087, 0.302, 0.062, 0.   , 0.   , 0.184, 0.143, 0.   , 0.143, 0.083],
       [0.058, 0.21 , 0.21 , 0.055, 0.406, 0.   , 0.083, 0.046, 0.009, 0.019, 0.009, 0.   ],
       [0.142, 0.017, 0.   , 0.   , 0.   , 0.295, 0.083, 0.   , 0.   , 0.184, 0.   , 0.   ],
       [0.113, 0.069, 0.017, 0.   , 0.062, 0.097, 0.333, 0.011, 0.   , 0.147, 0.   , 0.   ],
       [0.   , 0.017, 0.069, 0.175, 0.049, 0.   , 0.016, 0.287, 0.143, 0.   , 0.143, 0.083],
       [0.   , 0.   , 0.017, 0.175, 0.012, 0.   , 0.   , 0.184, 0.288, 0.   , 0.288, 0.278],
       [0.246, 0.017, 0.   , 0.   , 0.019, 0.295, 0.201, 0.   , 0.   , 0.32 , 0.   , 0.   ],
       [0.   , 0.   , 0.017, 0.175, 0.012, 0.   , 0.   , 0.184, 0.288,

$
\Gamma_2 M^2, 
$

In [311]:
M_2=tau_operation(power_matrix(M_1,2),2)
M_3=tau_operation(power_matrix(M_2,2),2)
M_4=tau_operation(power_matrix(M_3,2),2)


In [312]:
np.round(M_4,3)

array([[0.807, 0.04 , 0.015, 0.   , 0.034, 0.807, 0.806, 0.   , 0.   , 0.807, 0.   , 0.   ],
       [0.   , 0.09 , 0.092, 0.   , 0.088, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.085, 0.088, 0.   , 0.084, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.001, 0.001, 0.032, 0.001, 0.   , 0.   , 0.032, 0.031, 0.   , 0.031, 0.031],
       [0.   , 0.777, 0.798, 0.   , 0.786, 0.   , 0.001, 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.005, 0.   , 0.   , 0.   , 0.   , 0.005, 0.005, 0.   , 0.   , 0.005, 0.   , 0.   ],
       [0.003, 0.   , 0.   , 0.   , 0.   , 0.003, 0.003, 0.   , 0.   , 0.003, 0.   , 0.   ],
       [0.   , 0.   , 0.001, 0.024, 0.   , 0.   , 0.   , 0.024, 0.024, 0.   , 0.024, 0.024],
       [0.   , 0.   , 0.002, 0.471, 0.001, 0.   , 0.   , 0.471, 0.472, 0.   , 0.472, 0.472],
       [0.185, 0.005, 0.001, 0.   , 0.004, 0.185, 0.184, 0.   , 0.   , 0.185, 0.   , 0.   ],
       [0.   , 0.   , 0.002, 0.471, 0.001, 0.   , 0.   , 0.471, 0.472,

In [313]:
np.sum(A,axis=0)

array([4., 3., 3., 4., 4., 2., 3., 4., 4., 3., 4., 2.])

In [314]:
def squaring(M,r) : 
    M_new = copy.deepcopy(M)
    for i in range(r-1) : 
        M_new = tau_operation(power_matrix(M_new,2),2)

    return M_new

In [320]:
np.round(
    squaring(M,90)
,3)

array([[1. , 0. , 0. , 0. , 0. , 1. , 1. , 0. , 0. , 1. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 1. , 1. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0. , 0. , 0. , 0.5, 0.5, 0. , 0.5, 0.5],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0. , 0. , 0. , 0.5, 0.5, 0. , 0.5, 0.5],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]])