In [1]:
from evaluation import *

In [204]:
filename = './xes/PrepaidTravelCost.xes'

In [205]:
log, VARIANT = read_xes(filename)


=READ THE XES FILE
length of log 2099 
length of event 18246 
number of variants : 202


In [25]:
def cosine_similarity(v1,v2) : 
    return np.dot(v1,v2) / (np.linalg.norm(v1) *np.linalg.norm(v1))

In [206]:
case_statistics.get_variant_statistics(log)

[{'variant': 'B,C,H,A,G,F,D,E', 'count': 569},
 {'variant': 'B,C,J,H,A,G,K,F,D,E', 'count': 311},
 {'variant': 'B,C,M,N,A,G,F,D,E', 'count': 126},
 {'variant': 'B,C,J,M,N,A,G,K,F,D,E', 'count': 100},
 {'variant': 'A,G,K,F,D,E', 'count': 93},
 {'variant': 'B,P,H,A,Q,F,D,E', 'count': 90},
 {'variant': 'A,G,F,D,E', 'count': 84},
 {'variant': 'B,H,A,F,D,E', 'count': 79},
 {'variant': 'B,C,H,A,L,I,A,G,F,D,E', 'count': 53},
 {'variant': 'B,C,A,G,H,F,D,E', 'count': 43},
 {'variant': 'B,C,A,G,J,K,H,F,D,E', 'count': 28},
 {'variant': 'B,C,J,H,A,L,I,A,G,K,F,D,E', 'count': 26},
 {'variant': 'B,M,N,A,F,D,E', 'count': 21},
 {'variant': 'A,L,I', 'count': 20},
 {'variant': 'B,C,H,A,G,K,F,D,E', 'count': 19},
 {'variant': 'B,C,A,G,F,H,D,E', 'count': 14},
 {'variant': 'B,C,M,N,A,G,T,U,D,E', 'count': 13},
 {'variant': 'B,C,J,H,A,L,I', 'count': 13},
 {'variant': 'A,F,D,E', 'count': 13},
 {'variant': 'B,C,H,A,L,I', 'count': 12},
 {'variant': 'B,P,H,A,3,I,A,Q,F,D,E', 'count': 11},
 {'variant': 'B,P,M,N,A,Q,

In [215]:
for i in log[0].attributes.values() : print(i)

req for pay 73550
UNKNOWN
task 71977
organizational unit 65463
854.5798378437331
activity 505
UNKNOWN
budget 6198
UNKNOWN
project 503
req for pay 73550
organizational unit 65455
1979.272103997747
0
travel permit 73549
UNKNOWN
req for pay number 73551


In [251]:
variants_filter.apply(log, [VARIANT[0]])[0].attributes.values()

dict_values(['req for pay 36828', 'travel permit number 36823', 'task 36827', 'organizational unit 65463', 193.76527411003897, 'activity 505', 'task 427', 'budget 529', 'project 36824', 'project 503', 'req for pay 36828', 'organizational unit 65455', 2877.702090743153, 0, 'travel permit 36822', 'UNKNOWN', 'req for pay number 36829'])

In [241]:
v

'A,3,I'

In [20]:
vlog[0][0]

{'(case)_Item': '00010', '(case)_Goods_Receipt': 'true', '(case)_Item_Category': '3-way match, invoice after GR', '(case)_Document_Type': 'Standard PO', '(case)_Purch__Doc__Category_name': 'Purchase order', '(case)_Vendor': 'vendorID_0107', 'User': 'user_033', '(case)_Spend_area_text': 'Specialty Resins', '(case)_Spend_classification_text': 'PR', 'Cumulative_net_worth_(EUR)': '43301.0', '(case)_Sub_spend_area_text': 'Alkyd Resins', 'time:timestamp': datetime.datetime(2018, 1, 2, 7, 23, tzinfo=datetime.timezone(datetime.timedelta(seconds=3600))), '(case)_Source': 'sourceSystemID_0000', '(case)_Company': 'companyID_0000', '(case)_GR-Based_Inv__Verif_': 'true', '(case)_Purchasing_Document': '4507000227', 'org:resource': 'user_033', 'concept:name': 'A', '(case)_Name': 'vendor_0107', 'lifecycle:transition': 'complete', '(case)_Item_Type': 'Standard'}

In [269]:
lst_features =[]
for v in VARIANT : 
    feature=[]
    for i in variants_filter.apply(log, [v])[0].attributes.values() : 
        feature.append(i)
    lst_features.append(feature)

In [270]:
import pandas as pd
data=pd.DataFrame(lst_features)

In [271]:
data

0                           1            2  \
0     req for pay 36828  travel permit number 36823   task 36827   
1     req for pay 16289  travel permit number 16288      UNKNOWN   
2      req for pay 7712   travel permit number 7711    task 6652   
3      req for pay 4544   travel permit number 4538      UNKNOWN   
4    req for pay 185740    travel permit number 424  task 185446   
..                  ...                         ...          ...   
197  req for pay 186216                     UNKNOWN      UNKNOWN   
198  req for pay 186113                     UNKNOWN  task 148121   
199  req for pay 186345                     UNKNOWN   task 10542   
200  req for pay 186322                     UNKNOWN      UNKNOWN   
201  req for pay 185404                     UNKNOWN      UNKNOWN   

                             3            4             5         6  \
0    organizational unit 65463   193.765274  activity 505  task 427   
1    organizational unit 65463  3422.610409       UNKNOWN   UNKNOWN   
2    organizational unit 65454   364.852114  activity 505  task 427   
3    organizational unit 65458    65.244734       UNKNOWN   UNKNOWN   
4    organizational unit 65469   243.648867  activity 505  task 427   
..                         ...          ...           ...       ...   
197  organizational unit 65462    73.932604       UNKNOWN   UNKNOWN   
198  organizational unit 65458  4230.460182  activity 505   UNKNOWN   
199  organizational unit 65456   387.624471  activity 505   UNKNOWN   
200  organizational unit 65482   102.983373       UNKNOWN   UNKNOWN   
201  organizational unit 65463  1112.095617       UNKNOWN   UNKNOWN   

               7              8               9                  10  \
0     budget 529  project 36824     project 503   req for pay 36828   
1    budget 8795        UNKNOWN     project 503   req for pay 16289   
2     budget 499   project 6649     project 503    req for pay 7712   
3     budget 922        UNKNOWN     project 503    req for pay 4544   
4     budget 425    project 426     project 503  req for pay 185740   
..           ...            ...             ...                 ...   
197      UNKNOWN        UNKNOWN  project 147582  req for pay 186216   
198      UNKNOWN        UNKNOWN  project 148216  req for pay 186113   
199      UNKNOWN        UNKNOWN  project 147546  req for pay 186345   
200      UNKNOWN        UNKNOWN  project 147620  req for pay 186322   
201      UNKNOWN        UNKNOWN         UNKNOWN  req for pay 185404   

                            11           12  13                   14       15  \
0    organizational unit 65455  2877.702091   0  travel permit 36822  UNKNOWN   
1    organizational unit 65455  4819.069725   0  travel permit 16287  UNKNOWN   
2    organizational unit 65460  1934.821819   0   travel permit 7710  UNKNOWN   
3    organizational unit 65458  3113.953197   0   travel permit 4537  UNKNOWN   
4    organizational unit 65454   923.081315   0    travel permit 423  UNKNOWN   
..                         ...          ...  ..                  ...      ...   
197                    UNKNOWN     0.000000   0              UNKNOWN  UNKNOWN   
198                    UNKNOWN     0.000000   0              UNKNOWN  UNKNOWN   
199                    UNKNOWN     0.000000   0              UNKNOWN  UNKNOWN   
200                    UNKNOWN     0.000000   0              UNKNOWN  UNKNOWN   
201                    UNKNOWN     0.000000   0              UNKNOWN  UNKNOWN   

                            16  
0     req for pay number 36829  
1     req for pay number 16290  
2      req for pay number 7713  
3      req for pay number 4545  
4    req for pay number 185741  
..                         ...  
197                    UNKNOWN  
198  req for pay number 186114  
199  req for pay number 186346  
200  req for pay number 186323  
201                    UNKNOWN  

[202 rows x 17 columns]

In [147]:
data_filtered = data.loc[:,[6,7,15]]

In [149]:
data_filtered[7] = data_filtered[7].astype('float')
data_filtered[7] = (data_filtered[7] - min(data_filtered[7])) / (max(data_filtered[7]) - min(data_filtered[7]))

In [275]:
data_final= pd.get_dummies(data)

In [276]:
n = len(data_final)
A=np.zeros((n,n))

In [281]:
for i in range(len(A)-1) : 
    for j in range(i+1, len(A)) : 
        sim = cosine_similarity(data_final.iloc[i], data_final.iloc[j])
        A[i,j] = sim
        A[j,i] = sim

In [158]:
from IPython.display import display_pretty, display_html, display_jpeg, display_png, display_json, display_latex, display_svg


In [159]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

In [160]:
import numpy as np
large_width = 400
np.set_printoptions(linewidth=large_width)

In [161]:
np.set_printoptions(precision=3)

In [162]:
import numpy as np

In [176]:
edges =[
    [6,10],
    [6,1],
    [10,7],
    [10,1],
    [7,1],
    [7,5],
    [5,2],
    [5,3],
    [1,2],
    [2,3],
    [5,8],
    [3,4],
    [5,8],
    [8,9],
    [8,4],
    [8,11],
    [11,4],
    [4,9],
    [11,9],
    [11,12],
    [12,11],
    [12,9],
]

In [177]:
N = np.zeros((13,13))

In [178]:
for e in edges : 
    N[e[0],e[1]] = 1
    N[e[1],e[0]] = 1

In [179]:
A=N[1:,:][:,1:]

In [180]:
B=A + np.identity(12)

In [181]:
M=col_norm(B)

In [182]:
M_G3=np.matmul(B,B.T)


In [163]:
import copy

In [170]:
def gamma_operation (M, r):
    M_new = copy.deepcopy(M.T)
    
    for i, row in enumerate(M_new) :
        M_new[i] = M_new[i] ** r / sum(row **r )
    return M_new.T

In [171]:
def col_norm (M):
    M_new = copy.deepcopy(M.T)
    for i, row in enumerate(M_new) :
        M_new[i] = M_new[i] / sum(row)
    return M_new.T

In [172]:
def power_matrix (M,r) :
    M_new = copy.deepcopy(M)
    for i in range(r-1) : 
        M_new = np.matmul(M_new, M)
    return M_new


$
\Gamma_2 M^2, 
$

In [309]:
M_1=gamma_operation(power_matrix(M,2),2)

In [310]:
M_1

array([[0.38 , 0.087, 0.027, 0.   , 0.077, 0.295, 0.201, 0.   , 0.   , 0.32 , 0.   , 0.   ],
       [0.047, 0.347, 0.21 , 0.017, 0.15 , 0.019, 0.066, 0.011, 0.   , 0.012, 0.   , 0.   ],
       [0.014, 0.21 , 0.347, 0.055, 0.15 , 0.   , 0.016, 0.046, 0.009, 0.   , 0.009, 0.   ],
       [0.   , 0.027, 0.087, 0.302, 0.062, 0.   , 0.   , 0.184, 0.143, 0.   , 0.143, 0.083],
       [0.058, 0.21 , 0.21 , 0.055, 0.406, 0.   , 0.083, 0.046, 0.009, 0.019, 0.009, 0.   ],
       [0.142, 0.017, 0.   , 0.   , 0.   , 0.295, 0.083, 0.   , 0.   , 0.184, 0.   , 0.   ],
       [0.113, 0.069, 0.017, 0.   , 0.062, 0.097, 0.333, 0.011, 0.   , 0.147, 0.   , 0.   ],
       [0.   , 0.017, 0.069, 0.175, 0.049, 0.   , 0.016, 0.287, 0.143, 0.   , 0.143, 0.083],
       [0.   , 0.   , 0.017, 0.175, 0.012, 0.   , 0.   , 0.184, 0.288, 0.   , 0.288, 0.278],
       [0.246, 0.017, 0.   , 0.   , 0.019, 0.295, 0.201, 0.   , 0.   , 0.32 , 0.   , 0.   ],
       [0.   , 0.   , 0.017, 0.175, 0.012, 0.   , 0.   , 0.184, 0.288,

$
\Gamma_2 M^2, 
$

In [311]:
M_2=tau_operation(power_matrix(M_1,2),2)
M_3=tau_operation(power_matrix(M_2,2),2)
M_4=tau_operation(power_matrix(M_3,2),2)


In [312]:
np.round(M_4,3)

array([[0.807, 0.04 , 0.015, 0.   , 0.034, 0.807, 0.806, 0.   , 0.   , 0.807, 0.   , 0.   ],
       [0.   , 0.09 , 0.092, 0.   , 0.088, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.085, 0.088, 0.   , 0.084, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.001, 0.001, 0.032, 0.001, 0.   , 0.   , 0.032, 0.031, 0.   , 0.031, 0.031],
       [0.   , 0.777, 0.798, 0.   , 0.786, 0.   , 0.001, 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.005, 0.   , 0.   , 0.   , 0.   , 0.005, 0.005, 0.   , 0.   , 0.005, 0.   , 0.   ],
       [0.003, 0.   , 0.   , 0.   , 0.   , 0.003, 0.003, 0.   , 0.   , 0.003, 0.   , 0.   ],
       [0.   , 0.   , 0.001, 0.024, 0.   , 0.   , 0.   , 0.024, 0.024, 0.   , 0.024, 0.024],
       [0.   , 0.   , 0.002, 0.471, 0.001, 0.   , 0.   , 0.471, 0.472, 0.   , 0.472, 0.472],
       [0.185, 0.005, 0.001, 0.   , 0.004, 0.185, 0.184, 0.   , 0.   , 0.185, 0.   , 0.   ],
       [0.   , 0.   , 0.002, 0.471, 0.001, 0.   , 0.   , 0.471, 0.472,

In [313]:
np.sum(A,axis=0)

array([4., 3., 3., 4., 4., 2., 3., 4., 4., 3., 4., 2.])

In [173]:
def squaring(M,r) : 
    M_new = copy.deepcopy(M)
    for i in range(r-1) : 
        M_new = gamma_operation(power_matrix(M_new,2),2)

    return M_new

In [203]:
np.round(
    squaring(M,100)
,3)

array([[1. , 0. , 0. , 0. , 0. , 1. , 1. , 0. , 0. , 1. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 1. , 1. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0. , 0. , 0. , 0.5, 0.5, 0. , 0.5, 0.5],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0. , 0. , 0. , 0.5, 0.5, 0. , 0.5, 0.5],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]])

In [284]:
result=np.round(
    squaring(A,100)
,3)

In [297]:
np.sum(result, axis=1).argmax()

91

In [301]:
VARIANT[result[91] * True]

TypeError: only integer scalar arrays can be converted to a scalar index

In [318]:
CS=[]

In [320]:
CS.append(np.array(VARIANT)[result[91]==1])

In [321]:
CS.append(np.array(VARIANT)[result[154] == 1])

In [322]:
CS.append(np.array(VARIANT)[189])

In [324]:
quality_measure(log,CS)

[0.9052763274408954,
 0.8625646816161946,
 0.5932837826344332,
 0.5342506664339292]