# PAPER TO BE IMPLEMENTED TO STUDY

In [54]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

In [55]:
import copy

In [56]:
from IPython.display import display_pretty, display_html, display_jpeg, display_png, display_json, display_latex, display_svg


In [57]:
import numpy as np
large_width = 400
np.set_printoptions(linewidth=large_width)

In [58]:
def gamma_operation (M, r):
    M_new = copy.deepcopy(M.T)
    
    for i, row in enumerate(M_new) :
        M_new[i] = M_new[i] ** r / sum(row **r )
    return M_new.T

In [59]:
def col_norm (M):
    M_new = copy.deepcopy(M.T)
    for i, row in enumerate(M_new) :
        M_new[i] = M_new[i] / sum(row)
    return M_new.T

In [60]:
def power_matrix (M,r) :
    M_new = copy.deepcopy(M)
    for i in range(r-1) : 
        M_new = np.matmul(M_new, M)
    return M_new


In [61]:
def squaring(M,r) : 
    M_new = copy.deepcopy(M)
    for i in range(r-1) : 
        M_new = gamma_operation(power_matrix(M_new,2),2)

    return M_new

In [161]:
np.set_printoptions(precision=3)

In [176]:
edges =[
    [6,10],
    [6,1],
    [10,7],
    [10,1],
    [7,1],
    [7,5],
    [5,2],
    [5,3],
    [1,2],
    [2,3],
    [5,8],
    [3,4],
    [5,8],
    [8,9],
    [8,4],
    [8,11],
    [11,4],
    [4,9],
    [11,9],
    [11,12],
    [12,11],
    [12,9],
]

In [177]:
N = np.zeros((13,13))

In [178]:
for e in edges : 
    N[e[0],e[1]] = 1
    N[e[1],e[0]] = 1

In [179]:
A=N[1:,:][:,1:]

In [180]:
B=A + np.identity(12)

In [181]:
M=col_norm(B)

In [182]:
M_G3=np.matmul(B,B.T)


$
\Gamma_2 M^2, 
$

In [309]:
M_1=gamma_operation(power_matrix(M,2),2)

In [310]:
M_1

array([[0.38 , 0.087, 0.027, 0.   , 0.077, 0.295, 0.201, 0.   , 0.   , 0.32 , 0.   , 0.   ],
       [0.047, 0.347, 0.21 , 0.017, 0.15 , 0.019, 0.066, 0.011, 0.   , 0.012, 0.   , 0.   ],
       [0.014, 0.21 , 0.347, 0.055, 0.15 , 0.   , 0.016, 0.046, 0.009, 0.   , 0.009, 0.   ],
       [0.   , 0.027, 0.087, 0.302, 0.062, 0.   , 0.   , 0.184, 0.143, 0.   , 0.143, 0.083],
       [0.058, 0.21 , 0.21 , 0.055, 0.406, 0.   , 0.083, 0.046, 0.009, 0.019, 0.009, 0.   ],
       [0.142, 0.017, 0.   , 0.   , 0.   , 0.295, 0.083, 0.   , 0.   , 0.184, 0.   , 0.   ],
       [0.113, 0.069, 0.017, 0.   , 0.062, 0.097, 0.333, 0.011, 0.   , 0.147, 0.   , 0.   ],
       [0.   , 0.017, 0.069, 0.175, 0.049, 0.   , 0.016, 0.287, 0.143, 0.   , 0.143, 0.083],
       [0.   , 0.   , 0.017, 0.175, 0.012, 0.   , 0.   , 0.184, 0.288, 0.   , 0.288, 0.278],
       [0.246, 0.017, 0.   , 0.   , 0.019, 0.295, 0.201, 0.   , 0.   , 0.32 , 0.   , 0.   ],
       [0.   , 0.   , 0.017, 0.175, 0.012, 0.   , 0.   , 0.184, 0.288,

$
\Gamma_2 M^2, 
$

In [311]:
M_2=tau_operation(power_matrix(M_1,2),2)
M_3=tau_operation(power_matrix(M_2,2),2)
M_4=tau_operation(power_matrix(M_3,2),2)


In [312]:
np.round(M_4,3)

array([[0.807, 0.04 , 0.015, 0.   , 0.034, 0.807, 0.806, 0.   , 0.   , 0.807, 0.   , 0.   ],
       [0.   , 0.09 , 0.092, 0.   , 0.088, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.085, 0.088, 0.   , 0.084, 0.   , 0.   , 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.   , 0.001, 0.001, 0.032, 0.001, 0.   , 0.   , 0.032, 0.031, 0.   , 0.031, 0.031],
       [0.   , 0.777, 0.798, 0.   , 0.786, 0.   , 0.001, 0.   , 0.   , 0.   , 0.   , 0.   ],
       [0.005, 0.   , 0.   , 0.   , 0.   , 0.005, 0.005, 0.   , 0.   , 0.005, 0.   , 0.   ],
       [0.003, 0.   , 0.   , 0.   , 0.   , 0.003, 0.003, 0.   , 0.   , 0.003, 0.   , 0.   ],
       [0.   , 0.   , 0.001, 0.024, 0.   , 0.   , 0.   , 0.024, 0.024, 0.   , 0.024, 0.024],
       [0.   , 0.   , 0.002, 0.471, 0.001, 0.   , 0.   , 0.471, 0.472, 0.   , 0.472, 0.472],
       [0.185, 0.005, 0.001, 0.   , 0.004, 0.185, 0.184, 0.   , 0.   , 0.185, 0.   , 0.   ],
       [0.   , 0.   , 0.002, 0.471, 0.001, 0.   , 0.   , 0.471, 0.472,

In [313]:
np.sum(A,axis=0)

array([4., 3., 3., 4., 4., 2., 3., 4., 4., 3., 4., 2.])

In [203]:
np.round(
    squaring(M,100)
,3)

array([[1. , 0. , 0. , 0. , 0. , 1. , 1. , 0. , 0. , 1. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 1. , 1. , 0. , 1. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0. , 0. , 0. , 0.5, 0.5, 0. , 0.5, 0.5],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ],
       [0. , 0. , 0. , 0.5, 0. , 0. , 0. , 0.5, 0.5, 0. , 0.5, 0.5],
       [0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. , 0. ]])

# PREPAID COST XES CLUSTERING

In [32]:
from evaluation import *

In [33]:
filename = './xes/PrepaidTravelCost.xes'

In [34]:
log, VARIANT = read_xes(filename)


=READ THE XES FILE
length of log 2099 
length of event 18246 
number of variants : 202


In [35]:
def cosine_similarity(v1,v2) : 
    return np.dot(v1,v2) / (np.linalg.norm(v1) *np.linalg.norm(v1))

In [36]:
case_statistics.get_variant_statistics(log)

[{'variant': 'B,C,H,A,G,F,D,E', 'count': 569},
 {'variant': 'B,C,J,H,A,G,K,F,D,E', 'count': 311},
 {'variant': 'B,C,M,N,A,G,F,D,E', 'count': 126},
 {'variant': 'B,C,J,M,N,A,G,K,F,D,E', 'count': 100},
 {'variant': 'A,G,K,F,D,E', 'count': 93},
 {'variant': 'B,P,H,A,Q,F,D,E', 'count': 90},
 {'variant': 'A,G,F,D,E', 'count': 84},
 {'variant': 'B,H,A,F,D,E', 'count': 79},
 {'variant': 'B,C,H,A,L,I,A,G,F,D,E', 'count': 53},
 {'variant': 'B,C,A,G,H,F,D,E', 'count': 43},
 {'variant': 'B,C,A,G,J,K,H,F,D,E', 'count': 28},
 {'variant': 'B,C,J,H,A,L,I,A,G,K,F,D,E', 'count': 26},
 {'variant': 'B,M,N,A,F,D,E', 'count': 21},
 {'variant': 'A,L,I', 'count': 20},
 {'variant': 'B,C,H,A,G,K,F,D,E', 'count': 19},
 {'variant': 'B,C,A,G,F,H,D,E', 'count': 14},
 {'variant': 'B,C,M,N,A,G,T,U,D,E', 'count': 13},
 {'variant': 'B,C,J,H,A,L,I', 'count': 13},
 {'variant': 'A,F,D,E', 'count': 13},
 {'variant': 'B,C,H,A,L,I', 'count': 12},
 {'variant': 'B,P,H,A,3,I,A,Q,F,D,E', 'count': 11},
 {'variant': 'B,P,M,N,A,Q,

In [13]:
lst = []
for l in log : 
    lst.append(l.attributes.values())


In [16]:
l.attributes.keys()

dict_keys(['Rfp_id', 'Permit travel permit number', 'Task', 'OrganizationalEntity', 'ReqedAmount', 'Activity', 'Permit TaskNumber', 'Permit BudgetNumber', 'Permit ProjectNumber', 'Project', 'concept:name', 'Permit OrganizationalEntity', 'Permit ReqedBudget', 'Cost Type', 'Permit id', 'Permit ActivityNumber', 'RfpNumber'])

In [14]:
import pandas as pd

In [17]:
pd.DataFrame(lst, columns=l.attributes.keys())

Rfp_id Permit travel permit number         Task  \
0      req for pay 73550                     UNKNOWN   task 71977   
1      req for pay 73552                     UNKNOWN   task 71977   
2      req for pay 76316  travel permit number 76315      UNKNOWN   
3      req for pay 73536                     UNKNOWN   task 11190   
4     req for pay 185372    travel permit number 424   task 47027   
...                  ...                         ...          ...   
2094  req for pay 186623    travel permit number 424      UNKNOWN   
2095   req for pay 13067  travel permit number 13066      UNKNOWN   
2096  req for pay 186629                     UNKNOWN      UNKNOWN   
2097  req for pay 186617                     UNKNOWN  task 152704   
2098  req for pay 186612                     UNKNOWN      UNKNOWN   

           OrganizationalEntity  ReqedAmount      Activity Permit TaskNumber  \
0     organizational unit 65463   854.579838  activity 505           UNKNOWN   
1     organizational unit 65463   854.579838  activity 505           UNKNOWN   
2     organizational unit 65463  1173.957795       UNKNOWN           UNKNOWN   
3     organizational unit 65463   790.552073  activity 505          task 427   
4     organizational unit 65457   456.433436  activity 505          task 427   
...                         ...          ...           ...               ...   
2094  organizational unit 65458   708.655586       UNKNOWN          task 427   
2095  organizational unit 65458  1026.634560       UNKNOWN           UNKNOWN   
2096  organizational unit 65458    34.647185       UNKNOWN           UNKNOWN   
2097  organizational unit 65468    26.196422  activity 505           UNKNOWN   
2098  organizational unit 65462    96.739075       UNKNOWN           UNKNOWN   

     Permit BudgetNumber Permit ProjectNumber         Project  \
0            budget 6198              UNKNOWN     project 503   
1            budget 6198              UNKNOWN     project 503   
2            budget 2233              UNKNOWN     project 503   
3             budget 899         project 2260     project 503   
4             budget 425          project 426     project 503   
...                  ...                  ...             ...   
2094          budget 425          project 426     project 503   
2095          budget 635              UNKNOWN     project 503   
2096             UNKNOWN              UNKNOWN  project 147546   
2097             UNKNOWN              UNKNOWN  project 147649   
2098             UNKNOWN              UNKNOWN  project 147531   

            concept:name Permit OrganizationalEntity  Permit ReqedBudget  \
0      req for pay 73550   organizational unit 65455         1979.272104   
1      req for pay 73552   organizational unit 65455         1979.272104   
2      req for pay 76316   organizational unit 65455         3553.601973   
3      req for pay 73536   organizational unit 65455         3627.364438   
4     req for pay 185372   organizational unit 65454          923.081315   
...                  ...                         ...                 ...   
2094  req for pay 186623   organizational unit 65454          923.081315   
2095   req for pay 13067   organizational unit 65458         1296.255757   
2096  req for pay 186629                     UNKNOWN            0.000000   
2097  req for pay 186617                     UNKNOWN            0.000000   
2098  req for pay 186612                     UNKNOWN            0.000000   

      Cost Type            Permit id Permit ActivityNumber  \
0             0  travel permit 73549               UNKNOWN   
1             0  travel permit 73549               UNKNOWN   
2             0  travel permit 76314               UNKNOWN   
3             0  travel permit 73535               UNKNOWN   
4             0    travel permit 423               UNKNOWN   
...         ...                  ...                   ...   
2094          0    travel permit 423               UNKNOWN   
2095          0  travel permit 13065  

In [22]:
lst=[]
for L in log : 
    for l in L : 
        lst.append(l.values())


In [25]:
pd.DataFrame(lst, columns=log[0][0].keys())

id  org:resource concept:name  \
0               st_step 73555_0  STAFF MEMBER            B   
1               st_step 73554_0  STAFF MEMBER            H   
2               st_step 73558_0  STAFF MEMBER            A   
3               st_step 73559_0  STAFF MEMBER            F   
4               st_step 73557_0  STAFF MEMBER            Z   
...                         ...           ...          ...   
18241          st_step 186614_0  STAFF MEMBER            A   
18242          st_step 186616_0  STAFF MEMBER            G   
18243          st_step 186615_0  STAFF MEMBER            F   
18244  rp_req for pay 186612_15        SYSTEM            D   
18245  rp_req for pay 186612_16        SYSTEM            E   

                  time:timestamp   org:role  
0      2017-01-09 14:48:43+01:00          E  
1      2017-01-09 14:48:55+01:00          S  
2      2017-01-12 11:40:27+01:00          E  
3      2017-01-12 11:41:59+01:00          S  
4      2017-01-12 11:53:07+01:00       MIS.  
...                          ...        ...  
18241  2018-12-30 20:16:15+01:00          E  
18242  2018-12-30 20:16:25+01:00      ADMIN  
18243  2019-01-14 15:09:11+01:00          S  
18244  2019-01-15 07:02:45+01:00  UNDEFINED  
18245  2019-01-17 17:31:44+01:00  UNDEFINED  

[18246 rows x 5 columns]

In [37]:
lst_features =[]
for v in VARIANT : 
    feature=[]
    for i in variants_filter.apply(log, [v])[0].attributes.values() : 
        feature.append(i)
    lst_features.append(feature)

In [38]:
import pandas as pd
data=pd.DataFrame(lst_features)

In [104]:
data_final= pd.get_dummies(data)

In [105]:
n = len(data_final)
A=np.zeros((n,n))

In [87]:
from sklearn import preprocessing
x = data_final[[4,12]].values
min_max_scaler = preprocessing.MinMaxScaler()
x_scaled = min_max_scaler.fit_transform(x)

data_final[4]=x_scaled[:,0]
data_final[12]=x_scaled[:,1]

In [106]:
for i in range(len(A)-1) : 
    for j in range(i+1, len(A)) : 
        sim = cosine_similarity(data_final.iloc[i], data_final.iloc[j])
        A[i,j] = sim
        A[j,i] = sim

In [107]:
result=np.round(
    squaring(A,100)
,3)

In [110]:
CS=[]

In [111]:
CS.append(np.array(VARIANT)[result[91]==1])

In [112]:
CS.append(np.array(VARIANT)[result[154] == 1])

In [113]:
CS.append(np.array(VARIANT)[189])

In [114]:
quality_measure(log,CS)

[0.9052763274408954,
 0.8625646816161946,
 0.5931900538883159,
 0.5342506664339292]

In [64]:
CS=[]

In [65]:
CS.append(np.array(VARIANT)[result[91]==1])

In [66]:
CS.append(np.array(VARIANT)[result[154] == 1])

In [67]:
CS.append(np.array(VARIANT)[189])

In [68]:
quality_measure(log,CS)

[0.9052763274408954, 0.8625646816161946, 0.593279865002121, 0.5342506664339292]

In [68]:
quality_measure(log,CS)

[0.9052763274408954, 0.8625646816161946, 0.593279865002121, 0.5342506664339292]

In [137]:
np.linalg.eig(A)[1][0]

array([-2.29399987e-03, -1.69481465e-03, -3.77060373e-02,  4.02402846e-02, -9.76665929e-03,  9.39501760e-03,  1.45555103e-04,  1.35865653e-04,  2.38011297e-02,  1.93714899e-02,  5.75287483e-03,  4.02724282e-02, -8.90261956e-03,  3.69952258e-02,  2.02085827e-03,  1.47210280e-05,  2.97632791e-02,  9.90264348e-03,  1.94552834e-02, -1.01395560e-02, -2.13235070e-02, -1.63114751e-02,  5.73400486e-03,
       -1.47494141e-03,  4.59954930e-03,  2.26221367e-02, -2.93342405e-03,  6.07968762e-02, -1.49908188e-03, -9.78600957e-05, -1.45503002e-03, -1.04472860e-02, -3.12480763e-03,  3.52369421e-02, -5.55609333e-03, -4.21738109e-04,  1.20596421e-02,  4.96101202e-02,  6.92160803e-02, -3.74096063e-02, -1.50446217e-03, -2.03389052e-06,  7.03700224e-03,  2.56917929e-01,  6.42195264e-02, -2.96868528e-03,
        2.26918308e-03, -2.84357961e-02,  6.61516441e-03, -2.29563944e-03, -4.17345929e-03,  4.27342421e-04,  1.01215924e-04, -7.08110777e-03, -7.04118181e-03, -1.60547189e-03,  1.61502759e-03, -9.5058928

In [131]:
a=np.array([[0.3,0.7],[0.2,0.8]])

In [133]:
np.linalg.eig(a)

(array([0.1, 1. ]), array([[-0.96152395, -0.70710678],
        [ 0.27472113, -0.70710678]]))

# TEMP

In [123]:
v1=[1,1,1,1,1,0,0,   1, 1, 0, 0, 0, 0, 1,0.9  , 0.5]

In [124]:
v2=[1,1,1,1,1,0,0,0.4, 1, 0, 0, 0, 0, 1,0.47,    1]

In [125]:
cosine_similarity(v1,v2)

0.9186534216335541